Config = {} 

Config.AttachmentCrafting = {
    ["location"] = {x = -1825.37, y = 4528.52, z = 5.29, h = 271.94, r = 1.0},
    ["items"] = {
        [1] = {
            name = "weapon_dagger",
            amount = 1,
            info = {},
            costs = {
                ["steel"] = 5,
                ["iron"] = 5,
                ["rubber"] = 5,
            },
            type = "item",
            slot = 1,
            threshold = 0,
            points = 1,
        },
        [2] = {
            name = "weapon_bat",
            amount = 1,
            info = {},
            costs = {
                ["steel"] = 5,
                ["iron"] = 5,
                ["aluminum"] = 5,
        },
            type = "item",
            slot = 2,
            threshold = 0,
            points = 1,
        },
		[3] = {
            name = "weap_battleaxe",
            amount = 1,
            info = {},
            costs = {
                ["steel"] = 5,
                ["iron"] = 5,
                ["aluminum"] = 5,
        },
            type = "item",
            slot = 3,
            threshold = 0,
            points = 1,
        },
		[4] = {
            name = "weapon_bottle",
            amount = 1,
            info = {},
            costs = {
                ["steel"] = 5,
                ["iron"] = 5,
                ["aluminum"] = 5,
		},		
            type = "item",
            slot = 4,
            threshold = 0,
            points = 1,
        },
		[5] = {
            name = "weapon_crowbar",
            amount = 1,
            info = {},
            costs = {
                ["steel"] = 5,
                ["iron"] = 5,
                ["aluminum"] = 5,
        },
            type = "item",
            slot = 5,
            threshold = 0,
            points = 1,
        },
		[6] = {
            name = "weapon_flashlight",
            amount = 1,
            info = {},
            costs = {
                ["steel"] = 5,
                ["iron"] = 5,
                ["aluminum"] = 5,
        },
            type = "item",
            slot = 6,
            threshold = 0,
            points = 1,
        },
		[7] = {
            name = "weapon_golfclub",
            amount = 1,
            info = {},
            costs = {
                ["steel"] = 5,
                ["iron"] = 5,
                ["aluminum"] = 5,
        },
            type = "item",
            slot = 7,
            threshold = 0,
            points = 1,
        },
		[8] = {
            name = "weapon_hammer",
            amount = 1,
            info = {},
            costs = {
                ["steel"] = 5,
                ["iron"] = 5,
                ["aluminum"] = 5,
        },
            type = "item",
            slot = 8,
            threshold = 0,
            points = 1,
        },
		[9] = {
            name = "weapon_hatchet",
            amount = 1,
            info = {},
            costs = {
                ["steel"] = 5,
                ["iron"] = 5,
                ["aluminum"] = 5,
        },
            type = "item",
            slot = 9,
            threshold = 0,
            points = 1,
        },
		[10] = {
            name = "weapon_knife",
            amount = 1,
            info = {},
            costs = {
                ["steel"] = 5,
                ["iron"] = 5,
                ["aluminum"] = 5,
        },
            type = "item",
            slot = 10,
            threshold = 0,
            points = 1,
        },
		[11] = {
            name = "weapon_knuckle",
            amount = 1,
            info = {},
            costs = {
                ["steel"] = 5,
                ["iron"] = 5,
                ["aluminum"] = 5,
        },
            type = "item",
            slot = 11,
            threshold = 0,
            points = 1,
        },
		[12] = {
            name = "weapon_machete",
            amount = 1,
            info = {},
            costs = {
                ["steel"] = 5,
                ["iron"] = 5,
                ["aluminum"] = 5,
        },
            type = "item",
            slot = 12,
            threshold = 0,
            points = 1,
        },
		[13] = {
            name = "weapon_nightstick",
            amount = 1,
            info = {},
            costs = {
                ["steel"] = 5,
                ["iron"] = 5,
                ["aluminum"] = 5,
        },
            type = "item",
            slot = 13,
            threshold = 0,
            points = 1,
        },
		[14] = {
            name = "weapon_wrench",
            amount = 1,
            info = {},
            costs = {
                ["steel"] = 5,
                ["iron"] = 5,
                ["aluminum"] = 5,
        },
            type = "item",
            slot = 14,
            threshold = 0,
            points = 1,
        },
		[15] = {
            name = "weapon_poolcue",
            amount = 1,
            info = {},
            costs = {
                ["steel"] = 5,
                ["iron"] = 5,
                ["aluminum"] = 5,
        },
            type = "item",
            slot = 15,
            threshold = 0,
            points = 1,
        },
		[16] = {
            name = "weapon_stone_hatchet",
            amount = 1,
            info = {},
            costs = {
                ["steel"] = 5,
                ["iron"] = 5,
                ["aluminum"] = 5,
        },
            type = "item",
            slot = 16,
            threshold = 0,
            points = 1,
        },
		[17] = {
            name = "weapon_switchblade",
            amount = 1,
            info = {},
            costs = {
                ["steel"] = 5,
                ["iron"] = 5,
                ["aluminum"] = 5,
        },
            type = "item",
            slot = 17,
            threshold = 0,
            points = 1,
        },
		[18] = {
            name = "weapon_appistol",
            amount = 1,
            info = {},
            costs = {
                ["steel"] = 40,
                ["iron"] = 40,
                ["aluminum"] = 40,
            },
            type = "item",
            slot = 18,
            threshold = 0,
            points = 1,
        },
		[19] = {
            name = "weapon_doubleaction",
            amount = 1,
            info = {},
            costs = {
                ["steel"] = 35,
                ["iron"] = 35,
                ["aluminum"] = 35,
        },
            type = "item",
            slot = 19,
            threshold = 0,
            points = 1,
        },
		[20] = {
            name = "weapon_heavypistol",
            amount = 1,
            info = {},
            costs = {
                ["steel"] = 30,
                ["iron"] = 30,
                ["aluminum"] = 30,
        },
            type = "item",
            slot = 20,
            threshold = 0,
            points = 1,
        },
        [21] = {
            name = "weapon_revolver",
            amount = 1,
            info = {},
            costs = {
                ["steel"] = 35,
                ["iron"] = 35,
                ["aluminum"] = 35,
        },
            type = "item",
            slot = 21,
            threshold = 0,
            points = 1,
        },
        [22] = {
            name = "weapon_revolver_mk2",
            amount = 1,
            info = {},
            costs = {
                ["steel"] = 45,
                ["iron"] = 45,
                ["aluminum"] = 45,
        },
            type = "item",
            slot = 22,
            threshold = 0,
            points = 1,
        },
        [23] = {
            name = "weapon_marksmanpistol",
            amount = 1,
            info = {},
            costs = {
                ["steel"] = 30,
                ["iron"] = 30,
                ["aluminum"] = 30,
        },
            type = "item",
            slot = 23,
            threshold = 0,
            points = 1,
        },
        [24] = {
            name = "weapon_pistol50",
            amount = 1,
            info = {},
            costs = {
                ["steel"] = 35,
                ["iron"] = 35,
                ["aluminum"] = 35,
        },
            type = "item",
            slot = 24,
            threshold = 0,
            points = 1,
        },
        [25] = {
            name = "weapon_pistol_mk2",
            amount = 1,
            info = {},
            costs = {
                ["steel"] = 45,
                ["iron"] = 45,
                ["aluminum"] = 45,
        },
            type = "item",
            slot = 25,
            threshold = 0,
            points = 1,
        },
        [26] = {
            name = "weapon_snspistol_mk2",
            amount = 1,
            info = {},
            costs = {
                ["steel"] = 30,
                ["iron"] = 30,
                ["aluminum"] = 30,
        },
            type = "item",
            slot = 26,
            threshold = 0,
            points = 1,
        },
        [27] = {
            name = "weapon_vintagepistol",
            amount = 1,
            info = {},
            costs = {
                ["steel"] = 35,
                ["iron"] = 35,
                ["aluminum"] = 35,
        },
            type = "item",
            slot = 27,
            threshold = 0,
            points = 1,
        },
        [28] = {
            name = "weapon_assaultshotgun",
            amount = 1,
            info = {},
            costs = {
                ["steel"] = 50,
                ["iron"] = 50,
                ["aluminum"] = 50,
        },
            type = "item",
            slot = 28,
            threshold = 0,
            points = 1,
        },
        [29] = {
            name = "weapon_bullpupshotgun",
            amount = 1,
            info = {},
            costs = {
                ["steel"] = 50,
                ["iron"] = 50,
                ["aluminum"] = 50,
        },
            type = "item",
            slot = 29,
            threshold = 0,
            points = 1,
        },
        [30] = {
            name = "weapon_dbshotgun",
            amount = 1,
            info = {},
            costs = {
                ["steel"] = 45,
                ["iron"] = 45,
                ["aluminum"] = 45,
        },
            type = "item",
            slot = 30,
            threshold = 0,
            points = 1,
        },
        [31] = {
            name = "weapon_heavyshotgun",
            amount = 1,
            info = {},
            costs = {
                ["steel"] = 50,
                ["iron"] = 50,
                ["aluminum"] = 50,
        },
            type = "item",
            slot = 31,
            threshold = 0,
            points = 1,
        },
        [32] = {
            name = "weapon_pumpshotgun",
            amount = 1,
            info = {},
            costs = {
                ["steel"] = 50,
                ["iron"] = 50,
                ["aluminum"] = 50,
        },
            type = "item",
            slot = 32,
            threshold = 0,
            points = 1,
        },
        [33] = {
            name = "weapon_pumpshotgun_mk2",
            amount = 1,
            info = {},
            costs = {
                ["steel"] = 50,
                ["iron"] = 50,
                ["aluminum"] = 50,
        },
            type = "item",
            slot = 33,
            threshold = 0,
            points = 1,
        },
        [34] = {
            name = "weapon_sawnoffshotgun",
            amount = 1,
            info = {},
            costs = {
                ["steel"] = 45,
                ["iron"] = 45,
                ["aluminum"] = 45,
        },
            type = "item",
            slot = 34,
            threshold = 0,
            points = 1,
        },
        [35] = {
            name = "weapon_autoshotgun",
            amount = 1,
            info = {},
            costs = {
                ["steel"] = 50,
                ["iron"] = 50,
                ["aluminum"] = 50,
        },
            type = "item",
            slot = 35,
            threshold = 0,
            points = 1,
        },
        [36] = {
            name = "weapon_assaultsmg",
            amount = 1,
            info = {},
            costs = {
                ["steel"] = 75,
                ["iron"] = 75,
                ["aluminum"] = 75,
        },
            type = "item",
            slot = 36,
            threshold = 0,
            points = 1,
        },
        [37] = {
            name = "weapon_combatmg",
            amount = 1,
            info = {},
            costs = {
                ["steel"] = 75,
                ["iron"] = 75,
                ["aluminum"] = 75,
        },
            type = "item",
            slot = 37,
            threshold = 0,
            points = 1,
        },
        [38] = {
            name = "weapon_combatmg_mk2",
            amount = 1,
            info = {},
            costs = {
                ["steel"] = 75,
                ["iron"] = 75,
                ["aluminum"] = 75,
        },
            type = "item",
            slot = 38,
            threshold = 0,
            points = 1,
        },
        [39] = {
            name = "weapon_combatpdw",
            amount = 1,
            info = {},
            costs = {
                ["steel"] = 75,
                ["iron"] = 75,
                ["aluminum"] = 75,
        },
            type = "item",
            slot = 39,
            threshold = 0,
            points = 1,
        },
        [40] = {
            name = "weapon_gusenberg",
            amount = 1,
            info = {},
            costs = {
                ["steel"] = 75,
                ["iron"] = 75,
                ["aluminum"] = 75,
        },
            type = "item",
            slot = 40,
            threshold = 0,
            points = 1,
        },
        [41] = {
            name = "weapon_machinepistol",
            amount = 1,
            info = {},
            costs = {
                ["steel"] = 75,
                ["iron"] = 50,
                ["aluminum"] = 75,
        },
            type = "item",
            slot = 41,
            threshold = 0,
            points = 1,
        },
        [42] = {
            name = "weapon_mg",
            amount = 1,
            info = {},
            costs = {
                ["steel"] = 75,
                ["iron"] = 75,
                ["aluminum"] = 75,
        },
            type = "item",
            slot = 42,
            threshold = 0,
            points = 1,
        },
        [43] = {
            name = "weapon_microsmg",
            amount = 1,
            info = {},
            costs = {
                ["steel"] = 75,
                ["iron"] = 75,
                ["aluminum"] = 75,
        },
            type = "item",
            slot = 43,
            threshold = 0,
            points = 1,
        },
        [44] = {
            name = "weapon_minismg",
            amount = 1,
            info = {},
            costs = {
                ["steel"] = 75,
                ["iron"] = 75,
                ["aluminum"] = 75,
        },
            type = "item",
            slot = 44,
            threshold = 0,
            points = 1,
        },
        [45] = {
            name = "weapon_smg",
            amount = 1,
            info = {},
            costs = {
                ["steel"] = 75,
                ["iron"] = 75,
                ["aluminum"] = 75,
        },
            type = "item",
            slot = 45,
            threshold = 0,
            points = 1,
        },
        [46] = {
            name = "weapon_smg_mk2",
            amount = 1,
            info = {},
            costs = {
                ["steel"] = 75,
                ["iron"] = 75,
                ["aluminum"] = 75,
        },
            type = "item",
            slot = 46,
            threshold = 0,
            points = 1,
        },
        [47] = {
            name = "weapon_advancedrifle",
            amount = 1,
            info = {},
            costs = {
                ["steel"] = 125,
                ["iron"] = 125,
                ["aluminum"] = 125,
        },
            type = "item",
            slot = 47,
            threshold = 0,
            points = 1,
        },
        [48] = {
            name = "weapon_assaultrifle",
            amount = 1,
            info = {},
            costs = {
                ["steel"] = 125,
                ["iron"] = 125,
                ["aluminum"] = 125,
        },
            type = "item",
            slot = 48,
            threshold = 0,
            points = 1,
        },
        [49] = {
            name = "weapon_assaultrifle_mk2",
            amount = 1,
            info = {},
            costs = {
                ["steel"] = 125,
                ["iron"] = 125,
                ["aluminum"] = 125,
        },
            type = "item",
            slot = 49,
            threshold = 0,
            points = 1,
        },
        [50] = {
            name = "weapon_bullpuprifle",
            amount = 1,
            info = {},
            costs = {
                ["steel"] = 125,
                ["iron"] = 125,
                ["aluminum"] = 125,
        },
            type = "item",
            slot = 50,
            threshold = 0,
            points = 1,
        },
        [51] = {
            name = "weapon_bullpuprifle_mk2",
            amount = 1,
            info = {},
            costs = {
                ["steel"] = 125,
                ["iron"] = 125,
                ["aluminum"] = 125,
        },
            type = "item",
            slot = 51,
            threshold = 0,
            points = 1,
        },
        [52] = {
            name = "weapon_carbinerifle_mk2",
            amount = 1,
            info = {},
            costs = {
                ["steel"] = 125,
                ["iron"] = 125,
                ["aluminum"] = 125,
        },
            type = "item",
            slot = 52,
            threshold = 0,
            points = 1,
        },
        [53] = {
            name = "weapon_compactrifle",
            amount = 1,
            info = {},
            costs = {
                ["steel"] = 125,
                ["iron"] = 125,
                ["aluminum"] = 125,
        },
            type = "item",
            slot = 53,
            threshold = 0,
            points = 1,
        },
        [54] = {
            name = "weapon_specialcarbine",
            amount = 1,
            info = {},
            costs = {
                ["steel"] = 125,
                ["iron"] = 125,
                ["aluminum"] = 125,
            },
            type = "item",
            slot = 54,
            threshold = 0,
            points = 1,
        },
        [55] = {
            name = "weapon_specialcarbine_mk2",
            amount = 1,
            info = {},
            costs = {
                ["steel"] = 125,
                ["iron"] = 125,
                ["aluminum"] = 125,
            },
            type = "item",
            slot = 55,
            threshold = 0,
            points = 1,
        },
        [56] = {
            name = "weapon_molotov",
            amount = 1,
            info = {},
            costs = {
                ["glass"] = 10,
                ["teflon"] = 10,
                ["lighter"] = 1,
            },
            type = "item",
            slot = 56,
            threshold = 0,
            points = 1,
        },
        [57] = {
            name = "pistol_ammo",
            amount = 1,
            info = {},
            costs = {
                ["steel"] = 3,
                ["iron"] = 3,
                ["aluminum"] = 3,
            },
            type = "item",
            slot = 57,
            threshold = 0,
            points = 1,
        },
        [58] = {
            name = "rifle_ammo",
            amount = 1,
            info = {},
            costs = {
                ["steel"] = 8,
                ["iron"] = 8,
                ["aluminum"] = 8,
            },
            type = "item",
            slot = 58,
            threshold = 0,
            points = 1,
        },
        [59] = {
            name = "smg_ammo",
            amount = 1,
            info = {},
            costs = {
                ["steel"] = 5,
                ["iron"] = 5,
                ["aluminum"] = 5,
            },
            type = "item",
            slot = 59,
            threshold = 0,
            points = 1,     
        },
        [60] = {
            name = "shotgun_ammo",
            amount = 1,
            info = {},
            costs = {
                ["steel"] = 10,
                ["iron"] = 10,
                ["aluminum"] = 10,
            },
            type = "item",
            slot = 60,
            threshold = 0,
            points = 1,
        },
        [61] = {
            name = "mg_ammo",
            amount = 1,
            info = {},
            costs = {
                ["steel"] = 12,
                ["iron"] = 12,
                ["aluminum"] = 12,
            },
            type = "item",
            slot = 61,
            threshold = 0,
            points = 1,
        },
        [62] = {
            name = "pistol_suppressor",
            amount = 1,
            info = {},
            costs = {
                ["steel"] = 15,
                ["iron"] = 15,
                ["rubber"] = 15,
            },
            type = "item",
            slot = 62,
            threshold = 0,
            points = 1,
        },
        [63] = {
            name = "pistol_extendedclip",
            amount = 1,
            info = {},
            costs = {
                ["steel"] = 20,
                ["iron"] = 20,
                ["aluminum"] = 20,
            },
            type = "item",
            slot = 63,
            threshold = 0,
            points = 1,
        },
        [64] = {
            name = "pistol_flashlight",
            amount = 1,
            info = {},
            costs = {
                ["steel"] = 10,
                ["iron"] = 10,
                ["wires"] = 10,
            },
            type = "item",
            slot = 64,
            threshold = 0,
            points = 1,
        },
        [65] = {
            name = "pistol_compensator",
            amount = 1,
            info = {},
            costs = {
                ["steel"] = 10,
                ["iron"] = 10,
                ["aluminum"] = 10,
            },
            type = "item",
            slot = 65,
            threshold = 0,
            points = 1,
        },
        [66] = {
            name = "pistol_scope",
            amount = 1,
            info = {},
            costs = {
                ["steel"] = 10,
                ["iron"] = 10,
                ["wires"] = 10,
            },
            type = "item",
            slot = 66,
            threshold = 0,
            points = 1,
        },
        [67] = {
            name = "pistol_sight",
            amount = 1,
            info = {},
            costs = {
                ["steel"] = 10,
                ["iron"] = 10,
                ["aluminum"] = 10,
            },
            type = "item",
            slot = 67,
            threshold = 0,
            points = 1,
        },
        [68] = {
            name = "pistol_mountedscope",
            amount = 1,
            info = {},
            costs = {
                ["steel"] = 10,
                ["iron"] = 10,
                ["wires"] = 10,
            },
            type = "item",
            slot = 68,
            threshold = 0,
            points = 1,
        },
        [69] = {
            name = "pistol_drummag",
            amount = 1,
            info = {},
            costs = {
                ["steel"] = 25,
                ["iron"] = 25,
                ["aluminum"] = 25,
            },
            type = "item",
            slot = 69,
            threshold = 0,
            points = 1,
        },
        [70] = {
            name = "rifle_extendedclip",
            amount = 1,
            info = {},
            costs = {
                ["steel"] = 20,
                ["iron"] = 20,
                ["aluminum"] = 20,
            },
            type = "item",
            slot = 70,
            threshold = 0,
            points = 1,
        },
        [71] = {
            name = "rifle_drummag",
            amount = 1,
            info = {},
            costs = {
                ["steel"] = 25,
                ["iron"] = 25,
                ["aluminum"] = 25,
            },
            type = "item",
            slot = 71,
            threshold = 0,
            points = 1,
        },
        [72] = {
            name = "rifle_suppressor",
            amount = 1,
            info = {},
            costs = {
                ["steel"] = 15,
                ["iron"] = 15,
                ["rubber"] = 15,
            },
            type = "item",
            slot = 72,
            threshold = 0,
            points = 1,
        },
        [73] = {
            name = "rifle_flashlight",
            amount = 1,
            info = {},
            costs = {
                ["steel"] = 10,
                ["iron"] = 10,
                ["wires"] = 10,
            },
            type = "item",
            slot = 73,
            threshold = 0,
            points = 1,
        },
        [74] = {
            name = "rifle_smallscope",
            amount = 1,
            info = {},
            costs = {
                ["steel"] = 10,
                ["iron"] = 10,
                ["wires"] = 10,
            },
            type = "item",
            slot = 74,
            threshold = 0,
            points = 1,
        },
        [75] = {
            name = "rifle_scope",
            amount = 1,
            info = {},
            costs = {
                ["steel"] = 10,
                ["iron"] = 10,
                ["wires"] = 10,
            },
            type = "item",
            slot = 75,
            threshold = 0,
            points = 1,
        },
        [76] = {
            name = "rifle_grip",
            amount = 1,
            info = {},
            costs = {
                ["steel"] = 15,
                ["iron"] = 15,
                ["rubber"] = 15,
            },
            type = "item",
            slot = 76,
            threshold = 0,
            points = 1,
        },
        [77] = {
            name = "rifle_largescope",
            amount = 1,
            info = {},
            costs = {
                ["steel"] = 10,
                ["iron"] = 10,
                ["wires"] = 10,
            },
            type = "item",
            slot = 77,
            threshold = 0,
            points = 1,
        },
        [78] = {
            name = "rifle_sight",
            amount = 1,
            info = {},
            costs = {
                ["steel"] = 10,
                ["iron"] = 10,
                ["wires"] = 10,
            },
            type = "item",
            slot = 78,
            threshold = 0,
            points = 1,
        },
        [79] = {
            name = "rifle_mediumscope",
            amount = 1,
            info = {},
            costs = {
                ["steel"] = 10,
                ["iron"] = 10,
                ["wires"] = 10,
            },
            type = "item",
            slot = 79,
            threshold = 0,
            points = 1,
        },
        [80] = {
            name = "rifle_boxmagazine",
            amount = 1,
            info = {},
            costs = {
                ["steel"] = 30,
                ["iron"] = 30,
                ["aluminum"] = 30,
            },
            type = "item",
            slot = 80,
            threshold = 0,
            points = 1,
        },
        [81] = {
            name = "smg_grip",
            amount = 1,
            info = {},
            costs = {
                ["steel"] = 15,
                ["iron"] = 15,
                ["rubber"] = 15,
            },
            type = "item",
            slot = 81,
            threshold = 0,
            points = 1,
        },
        [82] = {
            name = "smg_drummag",
            amount = 1,
            info = {},
            costs = {
                ["steel"] = 25,
                ["iron"] = 25,
                ["aluminum"] = 25,
            },
            type = "item",
            slot = 82,
            threshold = 0,
            points = 1,
        },
        [83] = {
            name = "smg_sight",
            amount = 1,
            info = {},
            costs = {
                ["steel"] = 10,
                ["iron"] = 10,
                ["wires"] = 10,
            },
            type = "item",
            slot = 83,
            threshold = 0,
            points = 1,
        },
        [84] = {
            name = "smg_extendedclip",
            amount = 1,
            info = {},
            costs = {
                ["steel"] = 20,
                ["iron"] = 20,
                ["aluminum"] = 20,
            },
            type = "item",
            slot = 84,
            threshold = 0,
            points = 1,
        },
        [85] = {
            name = "smg_flashlight",
            amount = 1,
            info = {},
            costs = {
                ["steel"] = 10,
                ["iron"] = 10,
                ["wires"] = 10,
            },
            type = "item",
            slot = 85,
            threshold = 0,
            points = 1,
        },
        [86] = {
            name = "smg_scope",
            amount = 1,
            info = {},
            costs = {
                ["steel"] = 10,
                ["iron"] = 10,
                ["wires"] = 10,
            },
            type = "item",
            slot = 86,
            threshold = 0,
            points = 1,
        },
        [87] = {
            name = "smg_suppressor",
            amount = 1,
            info = {},
            costs = {
                ["steel"] = 15,
                ["iron"] = 15,
                ["rubber"] = 15,
            },
            type = "item",
            slot = 87,
            threshold = 0,
            points = 1,
        },
        [88] = {
            name = "smg_mediumscope",
            amount = 1,
            info = {},
            costs = {
                ["steel"] = 10,
                ["iron"] = 10,
                ["wires"] = 10,
            },
            type = "item",
            slot = 88,
            threshold = 0,
            points = 1,
        },
        [89] = {
            name = "shotgun_extendedclip",
            amount = 1,
            info = {},
            costs = {
                ["steel"] = 20,
                ["iron"] = 20,
                ["aluminum"] = 20,
            },
            type = "item",
            slot = 89,
            threshold = 0,
            points = 1,
        },
        [90] = {
            name = "shotgun_flashlight",
            amount = 1,
            info = {},
            costs = {
                ["steel"] = 10,
                ["iron"] = 10,
                ["wires"] = 10,
            },
            type = "item",
            slot = 90,
            threshold = 0,
            points = 1,
        },
        [91] = {
            name = "shotgun_suppressor",
            amount = 1,
            info = {},
            costs = {
                ["steel"] = 15,
                ["iron"] = 15,
                ["rubber"] = 15,
            },
            type = "item",
            slot = 91,
            threshold = 0,
            points = 1,
        },
        [92] = {
            name = "shotgun_compensator",
            amount = 1,
            info = {},
            costs = {
                ["steel"] = 10,
                ["iron"] = 10,
                ["aluminum"] = 10,
            },
            type = "item",
            slot = 92,
            threshold = 0,
            points = 1,
        },
        [93] = {
            name = "shotgun_grip",
            amount = 1,
            info = {},
            costs = {
                ["steel"] = 15,
                ["iron"] = 15,
                ["rubber"] = 15,
            },
            type = "item",
            slot = 93,
            threshold = 0,
            points = 1,
        },
        [94] = {
            name = "shotgun_drummag",
            amount = 1,
            info = {},
            costs = {
                ["steel"] = 25,
                ["iron"] = 25,
                ["aluminum"] = 25,
            },
            type = "item",
            slot = 94,
            threshold = 0,
            points = 1,
        },
        [95] = {
            name = "shotgun_smallscope",
            amount = 1,
            info = {},
            costs = {
                ["steel"] = 10,
                ["iron"] = 10,
                ["wires"] = 10,
            },
            type = "item",
            slot = 95,
            threshold = 0,
            points = 1,
        },
        [96] = {
            name = "mg_extendedclip",
            amount = 1,
            info = {},
            costs = {
                ["steel"] = 20,
                ["iron"] = 20,
                ["aluminum"] = 20,
            },
            type = "item",
            slot = 96,
            threshold = 0,
            points = 1,
        },
        [97] = {
            name = "mg_scope",
            amount = 1,
            info = {},
            costs = {
                ["steel"] = 10,
                ["iron"] = 10,
                ["wires"] = 10,
            },
            type = "item",
            slot = 97,
            threshold = 0,
            points = 1,
        },
        [98] = {
            name = "mg_grip",
            amount = 1,
            info = {},
            costs = {
                ["steel"] = 15,
                ["iron"] = 15,
                ["rubber"] = 15,
            },
            type = "item",
            slot = 98,
            threshold = 0,
            points = 1,
        },
        [99] = {
            name = "mg_sight",
            amount = 1,
            info = {},
            costs = {
                ["steel"] = 10,
                ["iron"] = 10,
                ["wires"] = 10,
            },
            type = "item",
            slot = 99,
            threshold = 0,
            points = 1,
        },
        [100] = {
            name = "mg_mediumscope",
            amount = 1,
            info = {},
            costs = {
                ["steel"] = 10,
                ["iron"] = 10,
                ["wires"] = 10,
            },
            type = "item",
            slot = 100,
            threshold = 0,
            points = 1,
        },
        [101] = {
            name = "mg_scope",
            amount = 1,
            info = {},
            costs = {
                ["steel"] = 10,
                ["iron"] = 10,
                ["wires"] = 10,
            },
            type = "item",
            slot = 101,
            threshold = 0,
            points = 1,
        },
    }
}

Config.CraftingItems = {
            [1] = {
            name = "laptop_h",
            amount = 100,
            info = {},
            costs = {
                ["plastic"] = 200,
                ["glass"] = 200,
                ["electronickit"] = 1, 
                ["wires"] = 20,
            },
            type = "item",
            slot = 1,
            threshold = 0,
            points = 1,
        },
        [2] = {
            name = "thermite",
            amount = 100,
            info = {},
            costs = {
                ["aluminumoxide"] = 100,
                ["ironoxide"] = 100,
                ["ceramicbowl"] = 1, 
            },
            type = "item",
            slot = 2,
            threshold = 0,
            points = 1,
        },
        [3] = {
            name = "timebomb",
            amount = 100,
            info = {},
            costs = {
             ["aluminum"] = 200,
             ["iron"] = 200,
             ["electronickit"] = 1,
             ["ducttape"] = 10, 
         },
         type = "item",
         slot = 3,
         threshold = 0,
         points = 1,
    },
    [4] = {
        name = "armor",
        amount = 100,
        info = {},
        costs = {
            ["teflon"] = 250,
            ["steel"] = 200,
            ["sewingkit"] = 1, 
        },
        type = "item",
        slot = 4,
        threshold = 0,
        points = 1,
    },
}